services:

    # Backend API
    img-recog-api:
        container_name: backend
        build: ./
        command: npm start
        working_dir: /usr/src/img-recog-api
        environment:
            POSTGRES_URI: postgres://img-recog:secret@postgres:5432/img-recog-docker
        links:
            - postgres
        ports:
            - "8080:8080"
        volumes:
            - ./:/usr/src/img-recog-api

    # Postgres
    postgres:
        container_name: postgres
        build: ./postgres
        environment:
            POSTGRES_USER: img-recog
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: img-recog-docker
            POSTGRES_HOST: postgres
        ports:
            - "5431:5432"        